### ISSUE TITLE
Result seems not match seasonal actually

### ISSUE THREAD

**Issue by c625473164** [chewxy/stl#2]
I think the data should be like this
https://www.statsmodels.org/dev/examples/notebooks/generated/stl_decomposition.html

**Comment by chewxy** [comment]
can you share your code and results?

**Comment by c625473164** [comment]
Sorry I just can't see the 'season' in your example. I guess seasonal data should be like [1,2,3,4,1,2,3,4,1,2,3,4] and the season is 4. But in your example seasonal data is monotone increasing

**Comment by chewxy** [comment]
I am assuming you mean this: https://github.com/chewxy/stl/blob/master/api_test.go#L48 ? You can change the periodicity and width parameters.

**Comment by c625473164** [comment]
Can you explain the width parameter and how should I set it. Thanks a lot.

**Comment by chewxy** [comment]
Per the [original paper](http://bit.ly/stl1990), the width parameter is "how many data points to consider for smoothing". For example, if you want to smooth over a year, and the rows represent months, then use width = 12

In the original, the widths are recommended to be odd numbers, but this library takes care of it
