### ISSUE TITLE
Linear function in loess

### ISSUE THREAD

**Issue by RishengDeng** [chewxy/stl#4]
Hi, it is very nice to see this project and I am trying to use STL in go. And I have something don't very clear about the linear function in loess. You said the implementation is slightly different from the typical math formula, but I still cannot understand the implementation through the comments of codes, could you please elaborate it clearly for me using the math formula? Thanks a lot!

**Comment by chewxy** [comment]
`Linear` is  a modified form of your basic linear regression - ![(\mathbf{X}^{\intercal}\mathbf{X})^{-1}(\mathbf{X}^{\intercal}\mathbf{y})](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%28%5Cmathbf%7BX%7D%5E%7B%5Cintercal%7D%5Cmathbf%7BX%7D%29%5E%7B-1%7D%28%5Cmathbf%7BX%7D%5E%7B%5Cintercal%7D%5Cmathbf%7By%7D%29).

First, consider the normal least squares regression. The formula above is the closed form solution of a problem written in matrix notation. What is the problem? Recall least squares can be defined as finding ![\mathbf{\beta}](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%5Cmathbf%7B%5Cbeta%7D) that minimizes the sum of squared errors: ![\sum_{i}^{n}(y_i - \mathbf{\beta}^{\intercal} \mathbf{x}_i)^2](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%5Csum_%7Bi%7D%5E%7Bn%7D%28y_i+-+%5Cmathbf%7B%5Cbeta%7D%5E%7B%5Cintercal%7D+%5Cmathbf%7Bx%7D_i%29%5E2).  

The problem can be thought of as two parts:

1. The prediction function
2. The minimization of the sum squared errors.

The prediction function is ![\mathbf{\beta}^{\intercal} \mathbf{x}](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%5Cmathbf%7B%5Cbeta%7D%5E%7B%5Cintercal%7D+%5Cmathbf%7Bx%7D). If you continue with the usual linear algebra and calculus (i.e finding ![\frac{\partial SSE }{\partial \mathbf{\beta}}](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%5Cfrac%7B%5Cpartial+SSE+%7D%7B%5Cpartial+%5Cmathbf%7B%5Cbeta%7D%7D)), you will find a closed form solution:   ![(\mathbf{X}^{\intercal}\mathbf{X})^{-1}(\mathbf{X}^{\intercal}\mathbf{y})](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%28%5Cmathbf%7BX%7D%5E%7B%5Cintercal%7D%5Cmathbf%7BX%7D%29%5E%7B-1%7D%28%5Cmathbf%7BX%7D%5E%7B%5Cintercal%7D%5Cmathbf%7By%7D%29)


In the case of loess however, we're using a (locally)-weighted linear regression. Our problem statement now reads ![\sum_{i}^{n}w_i(y_i - \mathbf{\beta}^{\intercal} \mathbf{x}_i)^2](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%5Csum_%7Bi%7D%5E%7Bn%7Dw_i%28y_i+-+%5Cmathbf%7B%5Cbeta%7D%5E%7B%5Cintercal%7D+%5Cmathbf%7Bx%7D_i%29%5E2). We need to minimize that loss term now. You also have two things to optimize for: ![\mathbf{\beta}](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%5Cmathbf%7B%5Cbeta%7D) and ![\mathbf{w}](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%5Cmathbf%7Bw%7D). 

The `Linear` function mainly deals with updating ![\mathbf{w}](https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%5Cmathbf%7Bw%7D), after fitting Y.  The entire function is just essentially solving 

![\frac{\partial \mathbf{w}(\mathbf{y} - \mathbf{\beta}^{\intercal} \mathbf{x})^2}{\partial w} = (y - \mathbf{\beta}^{\intercal}\mathbf{x})^2 ](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cfrac%7B%5Cpartial+%5Cmathbf%7Bw%7D%28%5Cmathbf%7By%7D+-+%5Cmathbf%7B%5Cbeta%7D%5E%7B%5Cintercal%7D+%5Cmathbf%7Bx%7D%29%5E2%7D%7B%5Cpartial+w%7D+%3D+%28y+-+%5Cmathbf%7B%5Cbeta%7D%5E%7B%5Cintercal%7D%5Cmathbf%7Bx%7D%29%5E2+)

With a few simplifications along the way

**Comment by RishengDeng** [comment]
Thanks for responding! 
There are some problems that I find in the code in my opinion, and I will elaborate below. 
First, in subcycle.go file, `cycleLength` should be equal to `periods + 1` rather than `periodicity + 1`. So in `setupWorkspace `function, `p` ought to be periodicity and `l` should be periods according to the paper, otherwise, the constraint of `i` is not useful. 
Second, still in subcycle.go file, in `do` function, I believe the `bwd` and `fwd` variable has some confusion. Although the default value of them is equal to 1. 
Don't know whether it's correct. It's very happy to help you make this project better if I have made some contribution.

**Comment by RishengDeng** [comment]
On the other hand, I am very confused that why the seasonal component is strange, it is always like a smooth line rather than an oscillating curve. I believe that some other people have proposed familiar issues about the seasonal component. Even though I use the same data and same parameters like width and periodicity, the result is totally different from the python _statsmodels_ implimentation, even though I have changed the code which I mentioned above.

**Comment by RishengDeng** [comment]
![20210715160414](https://user-images.githubusercontent.com/46927711/125752263-d454089d-cb85-4029-b8b2-500631d81cdf.jpg)
![20210715160445](https://user-images.githubusercontent.com/46927711/125752290-b360cd38-16a0-4d6a-b7c9-95df9475caf6.jpg)
